"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LiqERC721__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var LiqERC721__factory_1 = require("./LiqERC721__factory");
Object.defineProperty(exports, "LiqERC721__factory", { enumerable: true, get: function () { return LiqERC721__factory_1.LiqERC721__factory; } });
