"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC1155MetadataURI__factory = exports.ERC1155Burnable__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC1155Burnable__factory_1 = require("./ERC1155Burnable__factory");
Object.defineProperty(exports, "ERC1155Burnable__factory", { enumerable: true, get: function () { return ERC1155Burnable__factory_1.ERC1155Burnable__factory; } });
var IERC1155MetadataURI__factory_1 = require("./IERC1155MetadataURI__factory");
Object.defineProperty(exports, "IERC1155MetadataURI__factory", { enumerable: true, get: function () { return IERC1155MetadataURI__factory_1.IERC1155MetadataURI__factory; } });
