/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as liqErc20Sol from "./LIQ_ERC20.sol";
export type { liqErc20Sol };
import type * as nft from "./nft";
export type { nft };
