"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LiqERC1155__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var LiqERC1155__factory_1 = require("./LiqERC1155__factory");
Object.defineProperty(exports, "LiqERC1155__factory", { enumerable: true, get: function () { return LiqERC1155__factory_1.LiqERC1155__factory; } });
