/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as liqErc1155Sol from "./LIQ_ERC1155.sol";
export type { liqErc1155Sol };
import type * as liqErc721Sol from "./LIQ_ERC721.sol";
export type { liqErc721Sol };
